version: '3.8'

services:
  api: 
    container_name: entain-balancer-api  
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      postgres: 
        condition: service_healthy
    ports:
      - "${SERVER_PORT:-8080}:8080"
    volumes: []
    networks:
      - entain-network
    # Production-safe defaults:
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  postgres:  
    image: postgres:17
    container_name: entain-balancer-postgres 
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - entain-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s  # Added for slow-starting DBs

volumes:
  postgres_data:
    name: entain-balancer-postgres-data  

networks:
  entain-network:
    name: entain-balancer-network  
    driver: bridge